clc;
clear all;
close all;
x=input('Enter the sequence x(n)');
N=length(x);
y=fft(x,N);
disp(y);
mag=abs(y);
phase=angle(y);
subplot(2,2,1);
stem(x);
grid on;
title('Input Data Sequence x(n)');
subplot(2,2,3);
stem(mag);
grid on;
title('Magnitude Plot');
subplot(2,2,2);
stem(phase);
grid on;
title('Phase plot');
z=ifft(y,N);
mag1=real(z);
subplot(2,2,4);
stem(mag1);
grid on;
title('Signal Sequence constituted from Spectrum');
